version: '3'

services:
  redis:
    image: redis:7.2-alpine
    container_name: ynab-ic-redis
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - .docker/volumes/redis:/data
